/// Generated by spider on 2025-07-06 22:33:29.055926

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:shopping_app/core/constants/icon_path.dart';

void main() {
  test('icon_path assets test', () {
    expect(File(IconPath.iconCart).existsSync(), isTrue);
    expect(File(IconPath.iconFacebook).existsSync(), isTrue);
    expect(File(IconPath.iconGoogle).existsSync(), isTrue);
    expect(File(IconPath.iconHome).existsSync(), isTrue);
    expect(File(IconPath.iconTwitter).existsSync(), isTrue);
    expect(File(IconPath.iconWallet).existsSync(), isTrue);
    expect(File(IconPath.iconWishlist).existsSync(), isTrue);
  });
}
