/// Generated by spider on 2025-07-10 00:13:07.392619

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:shopping_app/core/constants/icon_path.dart';

void main() {
  test('icon_path assets test', () {
    expect(File(IconPath.iconAdidas).existsSync(), isTrue);
    expect(File(IconPath.iconBag).existsSync(), isTrue);
    expect(File(IconPath.iconBank).existsSync(), isTrue);
    expect(File(IconPath.iconCart).existsSync(), isTrue);
    expect(File(IconPath.iconDone).existsSync(), isTrue);
    expect(File(IconPath.iconEdit).existsSync(), isTrue);
    expect(File(IconPath.iconFacebook).existsSync(), isTrue);
    expect(File(IconPath.iconFila).existsSync(), isTrue);
    expect(File(IconPath.iconGoogle).existsSync(), isTrue);
    expect(File(IconPath.iconHeart).existsSync(), isTrue);
    expect(File(IconPath.iconHome).existsSync(), isTrue);
    expect(File(IconPath.iconLock).existsSync(), isTrue);
    expect(File(IconPath.iconLogout).existsSync(), isTrue);
    expect(File(IconPath.iconMaster).existsSync(), isTrue);
    expect(File(IconPath.iconMenu).existsSync(), isTrue);
    expect(File(IconPath.iconMic).existsSync(), isTrue);
    expect(File(IconPath.iconNike).existsSync(), isTrue);
    expect(File(IconPath.iconPaypal).existsSync(), isTrue);
    expect(File(IconPath.iconSearch).existsSync(), isTrue);
    expect(File(IconPath.iconSetting).existsSync(), isTrue);
    expect(File(IconPath.iconSun).existsSync(), isTrue);
    expect(File(IconPath.iconTwitter).existsSync(), isTrue);
    expect(File(IconPath.iconWallet).existsSync(), isTrue);
    expect(File(IconPath.iconWarring).existsSync(), isTrue);
    expect(File(IconPath.iconWishlist).existsSync(), isTrue);
  });
}
