/// Generated by spider on 2025-07-03 00:22:21.244831

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:shopping_app/core/constants/icon_path.dart';

void main() {
  test('icon_path assets test', () {
    expect(File(IconPath.iconCart).existsSync(), isTrue);
    expect(File(IconPath.iconHome).existsSync(), isTrue);
    expect(File(IconPath.iconSplash).existsSync(), isTrue);
    expect(File(IconPath.iconTitleSplash).existsSync(), isTrue);
    expect(File(IconPath.iconWallet).existsSync(), isTrue);
    expect(File(IconPath.iconWishlist).existsSync(), isTrue);
  });
}
