/// Generated by spider on 2025-07-03 00:22:21.279964

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:shopping_app/core/constants/image_path.dart';

void main() {
  test('image_path assets test', () {});
}
