/// Generated by spider on 2025-07-07 23:44:17.981927

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:shopping_app/core/constants/image_path.dart';

void main() {
  test('image_path assets test', () {
    expect(File(ImagePath.imgForgotPassword).existsSync(), isTrue);
    expect(File(ImagePath.imgMock1).existsSync(), isTrue);
    expect(File(ImagePath.imgMock2).existsSync(), isTrue);
    expect(File(ImagePath.imgMock3).existsSync(), isTrue);
    expect(File(ImagePath.imgMock4).existsSync(), isTrue);
    expect(File(ImagePath.imgOnboardBackgourd).existsSync(), isTrue);
    expect(File(ImagePath.imgPersion).existsSync(), isTrue);
    expect(File(ImagePath.imgSplash).existsSync(), isTrue);
    expect(File(ImagePath.imgTitleSplash).existsSync(), isTrue);
  });
}
