// Generated by spider on 2025-07-03 00:22:21.150278

class IconPath {
  IconPath._();

  static const String iconCart = 'assets/icons/icon_cart.svg';
  static const String iconHome = 'assets/icons/icon_home.svg';
  static const String iconSplash = 'assets/icons/icon_splash.png';
  static const String iconTitleSplash = 'assets/icons/icon_title_splash.png';
  static const String iconWallet = 'assets/icons/icon_wallet.svg';
  static const String iconWishlist = 'assets/icons/icon_wishlist.svg';
}
