// Generated by spider on 2025-07-10 11:20:45.321031

class IconPath {
  IconPath._();

  static const String iconAdidas = 'assets/icons/icon_adidas.svg';
  static const String iconBag = 'assets/icons/icon_bag.svg';
  static const String iconBank = 'assets/icons/icon_bank.png';
  static const String iconCart = 'assets/icons/icon_cart.svg';
  static const String iconDone = 'assets/icons/icon_done.svg';
  static const String iconEdit = 'assets/icons/icon_edit.svg';
  static const String iconFacebook = 'assets/icons/icon_facebook.svg';
  static const String iconFila = 'assets/icons/icon_fila.svg';
  static const String iconGoogle = 'assets/icons/icon_google.svg';
  static const String iconHeart = 'assets/icons/icon_heart.svg';
  static const String iconHome = 'assets/icons/icon_home.svg';
  static const String iconLock = 'assets/icons/icon_lock.svg';
  static const String iconLogout = 'assets/icons/icon_logout.svg';
  static const String iconMaster = 'assets/icons/icon_master.png';
  static const String iconMenu = 'assets/icons/icon_menu.svg';
  static const String iconMic = 'assets/icons/icon_mic.svg';
  static const String iconModifiy = 'assets/icons/icon_modifiy.svg';
  static const String iconNike = 'assets/icons/icon_nike.svg';
  static const String iconPaypal = 'assets/icons/icon_paypal.png';
  static const String iconSearch = 'assets/icons/icon_search.svg';
  static const String iconSetting = 'assets/icons/icon_setting.svg';
  static const String iconSun = 'assets/icons/icon_sun.svg';
  static const String iconTwitter = 'assets/icons/icon_twitter.svg';
  static const String iconWallet = 'assets/icons/icon_wallet.svg';
  static const String iconWarring = 'assets/icons/icon_warring.svg';
  static const String iconWishlist = 'assets/icons/icon_wishlist.svg';
}
