// Generated by spider on 2025-07-06 18:30:50.781260

class IconPath {
  IconPath._();

  static const String iconCart = 'assets/icons/icon_cart.svg';
  static const String iconFacebook = 'assets/icons/icon_facebook.svg';
  static const String iconGoogle = 'assets/icons/icon_google.svg';
  static const String iconHome = 'assets/icons/icon_home.svg';
  static const String iconTwitter = 'assets/icons/icon_twitter.svg';
  static const String iconWallet = 'assets/icons/icon_wallet.svg';
  static const String iconWishlist = 'assets/icons/icon_wishlist.svg';
}
