// Generated by spider on 2025-07-06 18:30:50.932189

class ImagePath {
  ImagePath._();

  static const String imgForgotPassword =
      'assets/images/img_forgot_password.svg';
  static const String imgSplash = 'assets/images/img_splash.png';
  static const String imgTitleSplash = 'assets/images/img_title_splash.png';
}
