// Generated by spider on 2025-08-12 21:49:22.687520

class ImagePath {
  ImagePath._();

  static const String imagUnion = 'assets/images/imag_union.png';
  static const String imagePhone = 'assets/images/image_phone.png';
  static const String imgCardBackground =
      'assets/images/img_card_background.png';
  static const String imgForgotPassword =
      'assets/images/img_forgot_password.svg';
  static const String imgMock1 = 'assets/images/img_mock_1.png';
  static const String imgMock2 = 'assets/images/img_mock_2.png';
  static const String imgMock3 = 'assets/images/img_mock_3.png';
  static const String imgMock4 = 'assets/images/img_mock_4.png';
  static const String imgOnboardBackgourd =
      'assets/images/img_onboard_backgourd.png';
  static const String imgPersion = 'assets/images/img_persion.png';
  static const String imgSplash = 'assets/images/img_splash.png';
  static const String imgTitleSplash = 'assets/images/img_title_splash.png';
  static const String imgUnion = 'assets/images/img_union.png';
  static const String productDetail = 'assets/images/product_detail.png';
  static const String productPreview1 = 'assets/images/product_preview_1.png';
  static const String productPreview2 = 'assets/images/product_preview_2.png';
  static const String productPreview3 = 'assets/images/product_preview_3.png';
  static const String productPreview4 = 'assets/images/product_preview_4.png';
}
