// Generated by spider on 2025-07-06 23:36:50.364616

class ImagePath {
  ImagePath._();

  static const String imgForgotPassword =
      'assets/images/img_forgot_password.svg';
  static const String imgOnboardBackgourd =
      'assets/images/img_onboard_backgourd.png';
  static const String imgPersion = 'assets/images/img_persion.png';
  static const String imgSplash = 'assets/images/img_splash.png';
  static const String imgTitleSplash = 'assets/images/img_title_splash.png';
}
